# .github/workflows/publish.yml
name: Generate a build and push to another branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
      - name: Push EN
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs-bg # The branch name where you want to push the assets
          FOLDER: docs/bg # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
      
      - name: Push BG
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs-en # The branch name where you want to push the assets
          FOLDER: docs/en # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message